export const countries = [
    { name: "AFGHANISTAN", code: "AF" },
    { name: "ALBANIA", code: "AL" },
    { name: "ALGERIA", code: "DZ" },
    { name: "AMERICAN SAMOA", code: "AS" },
    { name: "ANDORRA", code: "AD" },
    { name: "ANGOLA", code: "AO" },
    { name: "ANTARCTICA", code: "AQ" },
    { name: "ANTIGUA AND BARBUDA", code: "AG" },
    { name: "ARGENTINA", code: "AR" },
    { name: "ARMENIA", code: "AM" },
    { name: "ARUBA", code: "AW" },
    { name: "AUSTRALIA", code: "AU" },
    { name: "AUSTRIA", code: "AT" },
    { name: "AZERBAIJAN", code: "AZ" },
    { name: "BAHAMAS", code: "BS" },
    { name: "BAHRAIN", code: "BH" },
    { name: "BANGLADESH", code: "BD" },
    { name: "BARBADOS", code: "BB" },
    { name: "BELARUS", code: "BY" },
    { name: "BELGIUM", code: "BE" },
    { name: "BELIZE", code: "BZ" },
    { name: "BENIN", code: "BJ" },
    { name: "BERMUDA", code: "BM" },
    { name: "BHUTAN", code: "BT" },
    { name: "BOLIVIA", code: "BO" },
    { name: "BOSNIA AND HERZEGOVINA", code: "BA" },
    { name: "BOTSWANA", code: "BW" },
    { name: "BOUVET ISLAND", code: "BV" },
    { name: "BRAZIL", code: "BR" },
    { name: "BRITISH INDIAN OCEAN TERRITORY", code: "IO" },
    { name: "BRUNEI DARUSSALAM", code: "BN" },
    { name: "BULGARIA", code: "BG" },
    { name: "BURKINA FASO", code: "BF" },
    { name: "BURUNDI", code: "BI" },
    { name: "CAMBODIA", code: "KH" },
    { name: "CAMEROON", code: "CM" },
    { name: "CANADA", code: "CA" },
    { name: "CAPE VERDE", code: "CV" },
    { name: "CAYMAN ISLANDS", code: "KY" },
    { name: "CENTRAL AFRICAN REPUBLIC", code: "CF" },
    { name: "CHAD", code: "TD" },
    { name: "CHILE", code: "CL" },
    { name: "CHINA", code: "CN" },
    { name: "CHRISTMAS ISLAND", code: "CX" },
    { name: "COLOMBIA", code: "CO" },
    { name: "COMOROS", code: "KM" },
    { name: "CONGO", code: "CG" },
    { name: "CONGO, THE DEMOCRATIC REPUBLIC OF THE", code: "CD" },
    { name: "COOK ISLANDS", code: "CK" },
    { name: "COSTA RICA", code: "CR" },
    { name: "C\u00d4TE D'IVOIRE", code: "CI" },
    { name: "CROATIA", code: "HR" },
    { name: "CUBA", code: "CU" },
    { name: "CYPRUS", code: "CY" },
    { name: "CZECH REPUBLIC", code: "CZ" },
    { name: "DENMARK", code: "DK" },
    { name: "DJIBOUTI", code: "DJ" },
    { name: "DOMINICA", code: "DM" },
    { name: "DOMINICAN REPUBLIC", code: "DO" },
    { name: "ECUADOR", code: "EC" },
    { name: "EGYPT", code: "EG" },
    { name: "EL SALVADOR", code: "SV" },
    { name: "EQUATORIAL GUINEA", code: "GQ" },
    { name: "ERITREA", code: "ER" },
    { name: "ESTONIA", code: "EE" },
    { name: "ETHIOPIA", code: "ET" },
    { name: "FIJI", code: "FJ" },
    { name: "FINLAND", code: "FI" },
    { name: "FRANCE", code: "FR" },
    { name: "GERMANY", code: "DE" },
    { name: "GREECE", code: "GR" },
    { name: "GREENLAND", code: "GL" },
    { name: "GUATEMALA", code: "GT" },
    { name: "HAITI", code: "HT" },
    { name: "HONDURAS", code: "HN" },
    { name: "HONG KONG", code: "HK" },
    { name: "HUNGARY", code: "HU" },
    { name: "ICELAND", code: "IS" },
    { name: "INDIA", code: "IN" },
    { name: "INDONESIA", code: "ID" },
    { name: "IRELAND", code: "IE" },
    { name: "ISRAEL", code: "IL" },
    { name: "ITALY", code: "IT" },
    { name: "JAMAICA", code: "JM" },
    { name: "JAPAN", code: "JP" },
    { name: "KENYA", code: "KE" },
    { name: "KOREA, REPUBLIC OF", code: "KR" },
    { name: "KUWAIT", code: "KW" },
    { name: "LATVIA", code: "LV" },
    { name: "LEBANON", code: "LB" },
    { name: "LITHUANIA", code: "LT" },
    { name: "LUXEMBOURG", code: "LU" },
    { name: "MALAYSIA", code: "MY" },
    { name: "MALDIVES", code: "MV" },
    { name: "MALI", code: "ML" },
    { name: "MALTA", code: "MT" },
    { name: "MEXICO", code: "MX" },
    { name: "MONACO", code: "MC" },
    { name: "MONGOLIA", code: "MN" },
    { name: "MOROCCO", code: "MA" },
    { name: "NAMIBIA", code: "NA" },
    { name: "NEPAL", code: "NP" },
    { name: "NETHERLANDS", code: "NL" },
    { name: "NEW ZEALAND", code: "NZ" },
    { name: "NICARAGUA", code: "NI" },
    { name: "NIGER", code: "NE" },
    { name: "NIGERIA", code: "NG" },
    { name: "NORWAY", code: "NO" },
    { name: "OMAN", code: "OM" },
    { name: "PAKISTAN", code: "PK" },
    { name: "PANAMA", code: "PA" },
    { name: "PARAGUAY", code: "PY" },
    { name: "PERU", code: "PE" },
    { name: "PHILIPPINES", code: "PH" },
    { name: "POLAND", code: "PL" },
    { name: "PORTUGAL", code: "PT" },
    { name: "PUERTO RICO", code: "PR" },
    { name: "QATAR", code: "QA" },
    { name: "ROMANIA", code: "RO" },
    { name: "RUSSIAN FEDERATION", code: "RU" },
    { name: "SAUDI ARABIA", code: "SA" },
    { name: "SENEGAL", code: "SN" },
    { name: "SERBIA", code: "RS" },
    { name: "SINGAPORE", code: "SG" },
    { name: "SLOVAKIA", code: "SK" },
    { name: "SLOVENIA", code: "SI" },
    { name: "SOUTH AFRICA", code: "ZA" },
    { name: "SPAIN", code: "ES" },
    { name: "SRI LANKA", code: "LK" },
    { name: "SWEDEN", code: "SE" },
    { name: "SWITZERLAND", code: "CH" },
    { name: "TAIWAN", code: "TW" },
    { name: "THAILAND", code: "TH" },
    { name: "TUNISIA", code: "TN" },
    { name: "TURKEY", code: "TR" },
    { name: "UGANDA", code: "UG" },
    { name: "UKRAINE", code: "UA" },
    { name: "UNITED ARAB EMIRATES", code: "AE" },
    { name: "UNITED KINGDOM", code: "GB" },
    { name: "UNITED STATES", code: "US" },
    { name: "URUGUAY", code: "UY" },
    { name: "UZBEKISTAN", code: "UZ" },
    { name: "VENEZUELA", code: "VE" },
    { name: "VIET NAM", code: "VN" },
    { name: "YEMEN", code: "YE" },
    { name: "ZAMBIA", code: "ZM" },
    { name: "ZIMBABWE", code: "ZW" }
  ];
  